name: Publish and Deploy GameUtilities.Runtime

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy-unity:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_REPO: https://github.com/ADM87/GameUtilities.Unity.git

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish -c Release --output ./publish

      - name: Test
        run: dotnet test

      - name: Configure Git
        run: |
          git config --global user.email "<>"
          git config --global user.name "github-actions[bot]"

      - name: Clone Deployment Repository
        run: git clone $DEPLOYMENT_REPO ./deployment-repo

      - name: Copy Published Files
        run: cp ./publish/GameUtilities.Runtime.dll ./deployment-repo/Plugins/

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          cd ./deployment-repo
          git add -A
          git commit -m "GameUtilities.Runtime - ${{ github.ref }}"
          git push
