name: Deploy to GameUtilities.Unity

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RUNTIME_ROOT: './Runtime'
      RUNTIME_PROJ: 'GameUtilities.Runtime/GameUtilities.Runtime.csproj'
      RUNTIME_ARTIFACT: 'GameUtilities.Runtime.dll'
      UNITY_ROOT: './Unity'
      UNITY_REPO: 'ADM87/GameUtilities.Unity'
      TEST_ROOT: './Tests'
      TEST_PASS: 'GameUtilities.Tests/Tests.Pass/Tests.Pass.csproj'
      TEST_PASS_ARTIFACT: 'Tests.Pass.dll'
      TEST_FAIL: 'GameUtilities.Tests/Tests.Fail/Tests.Fail.csproj'
      TEST_FAIL_ARTIFACT: 'Tests.Fail.dll'
      PUBLISH_PATH: './Publish'
      DEPLOY_PATH: 'Plugins/GameUtilitiesRuntime'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.RUNTIME_ROOT }}

      - name: Fetch Version
        run: |
          cd ${{ env.RUNTIME_ROOT }}
          echo "VERSION_TAG=$(echo $(git tag -l --sort=-v:refname 'v[0-9]*.[0-9]*.[0-9]*' | head -n 1))" >> $GITHUB_ENV
          cd ..

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build & Test
        run: |
          dotnet build ${{ env.RUNTIME_ROOT }}/${{ env.TEST_PASS }} -o ${{ env.TEST_ROOT }}
          dotnet build ${{ env.RUNTIME_ROOT }}/${{ env.TEST_FAIL }} -o ${{ env.TEST_ROOT }}
          dotnet test ${{ env.TEST_ROOT }}/${{ env.TEST_PASS_ARTIFACT }} ${{ env.TEST_ROOT }}/${{ env.TEST_FAIL_ARTIFACT }}

      - name: Publish GameUtilities.Runtime
        run: dotnet publish ${{ env.RUNTIME_ROOT }}/${{ env.RUNTIME_PROJ}} -c Release -o ${{ env.PUBLISH_PATH }}

      - name: Checkout GameUtilities.Unity
        uses: actions/checkout@v4
        with:
          repository: ${{ env.UNITY_REPO }}
          path: ${{ env.UNITY_ROOT }}
          ref: 'main'

      - name: Copy GameUtilities.Runtime
        run: cp -r ${{ env.PUBLISH_PATH }}/${{ env.RUNTIME_ARTIFACT }} ${{ env.UNITY_ROOT }}/${{ env.DEPLOY_PATH }}

      - name: Commit & Push
        if: ${{ env.VERSION_TAG }}
        env:
          BRANCH_NAME: 'update-runtime-${{ env.VERSION_TAG }}'
        run: |
          cd ${{ env.UNITY_ROOT }}
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b ${{ env.BRANCH_NAME }}
          git add .
          git commit -m "Update GameUtilities.Runtime to ${{ env.VERSION_TAG }}"
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
          cd ..