name: Stamp Versioning

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  tag_version:
    if: ${{ github.event.pull_request.merged }} && ${{ github.base_ref == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create tag
        env:
          BRANCH_PREFIX: ${{ github.event.pull_request.head.ref }}=~ ^(major|minor|patch)/.*$
        if: env.BRANCH_PREFIX
        run: |
          echo "BRANCH_PREFIX=${BRANCH_PREFIX}"
          chmod +x ./.github/scripts/create_tag.sh
          echo "VERSION_TAG=$(echo $(./.github/scripts/create_tag.sh ${{ env.BRANCH_PREFIX }}))" >> $GITHUB_ENV

      - name: Push tag
        if: env.VERSION_TAG
        run: |
          echo "VERSION_TAG=${{ env.VERSION_TAG }}"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag ${{ env.VERSION_TAG }} -m "Version ${{ env.VERSION_TAG }}"
          git push origin ${{ env.VERSION_TAG }}
