name: Stamp Versioning

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tag_version:
    if: ${{ github.event.pull_request.merged }} && ${{ github.event.pull_request.base.ref == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Parse Branch Name
        id: parse_branch
        run: |
          branch_name=$(echo "${{ github.event.pull_request.base.ref }}" | awk -F'/' '{print $2}')
          if [[ $branch_name =~ ^(major|minor|patch)$ ]]; then
            echo "VERSION_TYPE=$branch_name" >> $GITHUB_ENV
          fi

      - name: Print Environment Variable
        if: env.VERSION_TYPE
        run: echo $VERSION_TYPE
